### ISSUE TITLE
How to auto scroll?

### ISSUE THREAD

**Issue by emjea** [robohorse/pagerbullet#1]
hi thanks to make this nice library.

i want to ask about auto scroll slide like this library https://github.com/Trinea/android-auto-scroll-view-pager?

Thanks before

**Comment by robohorse** [comment]
hmm...
Thanks for nice idea - i will think about it)

**Comment by FinnGu** [comment]
I don't think this library should be responsible for that.

You can easily use a Runnable and a Handler for that.
``` java

private PagerBullet pagerBullet;
private int currentPosition = 0;
private final Handler handler = new Handler();

private final Runnable runnable = new Runnable() {
    @Override
    public void run() {
        // Update your viewpager
        if (pagerBullet!= null) {
            // TODO: Loop through your items (e.g. reset your counter when reaching last item)
            pagerBullet.setCurrentItem(currentPosition);
            currentPosition++;
        }

        // This calls itself every 1000ms
        handler.postDelayed(this, 1000);
    }
};

// Setup your view, etc.

// Whenever you want, start the handler by calling
handler.post(runnable);

```

**Comment by robohorse** [comment]
yes. I think, that also required the following:
````java
 handler.removeCallbacks(yourRunnable);
````
while
onStop/onDetachedFromWindow

... sorry, i will try to find some time to support this feature

**Comment by FinnGu** [comment]
> yes. I think, that also required the following:
> handler.removeCallbacks(yourRunnable);
>while
>onStop/onDetachedFromWindow

You're right, I forgot about that part.

But as I said, I don't think your library is responsible for handling this.
