### ISSUE TITLE
Can I change dots color programmatically

### ISSUE THREAD

**Issue by haliltprkk** [robohorse/pagerbullet#11]
Because My fragments backgrounds are not the same.Thank you in advance

**Comment by robohorse** [comment]
Hi, yes you can) Just invoke [this method](https://github.com/robohorse/pagerbullet/blob/c40876d3a860353ed5de296d751e6f7e4148283d/src/main/java/com/robohorse/pagerbullet/PagerBullet.java#L88)

**Comment by haliltprkk** [comment]
thank you very much :)

2018-07-09 23:04 GMT+03:00 Vadim Shchenev <notifications@github.com>:
