### ISSUE TITLE
Disable Paging

### ISSUE THREAD

**Issue by haliltprkk** [robohorse/pagerbullet#12]
Hi,  is there any way to disable paging?

**Comment by robohorse** [comment]
can you explain plz: for what reason?

**Comment by haliltprkk** [comment]
I needed to viewpager not swipeable but also I needed to viewpager like you
made(I mean bottom points), and swipe issue will be handled with
button that is why I asked ,
But don't worry I have handled it somehow. Thank you for your attention :)

2018-08-07 14:23 GMT+03:00 Vadim Shchenev <notifications@github.com>:

**Comment by heath3n** [comment]
@haliltprkk I'm trying to achieve the same use case; mind explaining how you handled it for anyone else who ends up here?
