### ISSUE TITLE
Library not getting read by any repository

### ISSUE THREAD

**Issue by HimanshuImarticus** [robohorse/pagerbullet#18]
Could not find com.robohorse.pagerbullet:pagerbullet:1.0.5.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/robohorse/pagerbullet/pagerbullet/1.0.5/pagerbullet-1.0.5.pom
       - https://maven.google.com/com/robohorse/pagerbullet/pagerbullet/1.0.5/pagerbullet-1.0.5.pom
       - https://jitpack.io/com/robohorse/pagerbullet/pagerbullet/1.0.5/pagerbullet-1.0.5.pom
       - https://jcenter.bintray.com/com/robohorse/pagerbullet/pagerbullet/1.0.5/pagerbullet-1.0.5.pom
       - https://dl.google.com/dl/android/maven2/com/robohorse/pagerbullet/pagerbullet/1.0.5/pagerbullet-1.0.5.pom
       - https://plugins.gradle.org/m2/com/robohorse/pagerbullet/pagerbullet/1.0.5/pagerbullet-1.0.5.pom
       - file:/D:/Imarticus Learning/eckovation-app/eckovation/eckovation/app/libs/pagerbullet-1.0.5.jar
       - file:/D:/Imarticus Learning/eckovation-app/eckovation/eckovation/app/libs/pagerbullet.jar
       - https://clojars.org/repo/com/robohorse/pagerbullet/pagerbullet/1.0.5/pagerbullet-1.0.5.pom
     Required by:
         project :app

**Comment by robohorse** [comment]
Hey @HimanshuImarticus , thanks for your report. This project is deprecated for now. Please use the Jetpack Compose instead.
